In [1]:
import keras
from keras.models import Model, Sequential, load_model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, Conv3D, BatchNormalization
import tensorflow as tf
from keras import backend as K
import os
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
import pandas as pd
import os.path

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [4]:
os.listdir('/content/gdrive/MyDrive/Image Processing [PHB]/Image Classification/23-24/Dataset Klasifikasi/6 Cuaca/All')

['Clear', 'Haze', 'Underwater']

In [5]:
enc = OneHotEncoder()
enc.fit([[0], [1], [2]])
def names(number):
    if(number == 0):
        return 'Clear'
    elif(number== 1):
        return 'Haze'
    else:
        return 'Underwater'

In [11]:
data = []
paths = []
label = []
for r, d, f in os.walk("/content/gdrive/MyDrive/Image Processing [PHB]/Image Classification/23-24/Dataset Klasifikasi/6 Cuaca/All/Clear"):
    for file in f:
      if '.jpg' in file:
        paths.append(os.path.join(r, file))

for path in paths:
    img = Image.open(path)
    x = img.resize((128,128))
    x = np.array(x)
    if(x.shape == (128,128,3)):
        data.append(np.array(x))
        label.append(enc.transform([[0]]).toarray())

len(label)

15

In [12]:
paths = []
for r, d, f in os.walk("/content/gdrive/MyDrive/Image Processing [PHB]/Image Classification/23-24/Dataset Klasifikasi/6 Cuaca/All/Haze"):
    for file in f:
        if '.png' in file:
            paths.append(os.path.join(r, file))

for path in paths:
    img = Image.open(path)
    x = img.resize((128,128))
    x = np.array(x)
    if(x.shape == (128,128,3)):
        data.append(np.array(x))
        label.append(enc.transform([[1]]).toarray())

len(label)

30

In [13]:
paths = []
for r, d, f in os.walk('/content/gdrive/MyDrive/Image Processing [PHB]/Image Classification/23-24/Dataset Klasifikasi/6 Cuaca/All/Underwater'):
    for file in f:
        if '.png' in file:
            paths.append(os.path.join(r, file))

for path in paths:
    img = Image.open(path)
    x = img.resize((128,128))
    x = np.array(x)
    if(x.shape == (128,128,3)):
        data.append(np.array(x))
        label.append(enc.transform([[2]]).toarray())

len(label)

45

In [14]:
data = np.array(data)
data.shape

(45, 128, 128, 3)

In [15]:
label = np.array(label)
label = label.reshape(len(label),3)

label.shape

(45, 3)

In [23]:
x_train,x_test,y_train,y_test = train_test_split(data, label, test_size=0.2, shuffle=True, random_state=2)

In [24]:
print("x_train: "+str(x_train.shape))
print("x_test: "+str(x_test.shape))
print("y_train: "+str(y_train.shape))
print("y_test: "+str(y_test.shape))

x_train: (36, 128, 128, 3)
x_test: (9, 128, 128, 3)
y_train: (36, 3)
y_test: (9, 3)


In [25]:
y_train_ohe = np.array([np.where(r == 1)[0][0] for r in y_train])
y_test_ohe = np.array([np.where(r == 1)[0][0] for r in y_test])

In [26]:
print("y_train: "+str(y_train_ohe.shape))
print("y_test: "+str(y_test_ohe.shape))

y_train: (36,)
y_test: (9,)


In [27]:
#defining model
model=Sequential()

#Layer 1
#adding convolution layer
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(128,128,3)))
#adding pooling layer
model.add(MaxPooling2D(2,2))

#Layer 2


#Fully-Connected Layer
#adding fully connected layer
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(20,activation='relu'))
#adding output layer
model.add(Dense(3,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',  metrics= ['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 126, 126, 32)      896       
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 63, 63, 32)        0         
 g2D)                                                            
                                                                 
 flatten_1 (Flatten)         (None, 127008)            0         
                                                                 
 dense_3 (Dense)             (None, 100)               12700900  
                                                                 
 dense_4 (Dense)             (None, 20)                2020      
                                                                 
 dense_5 (Dense)             (None, 3)                 63        
                                                      

In [28]:
#fitting the model
model.fit(x_train,y_train_ohe, batch_size=8, epochs=10)

Epoch 1/10
5/5 [==============================] - 2s 13ms/step - loss: 2175.3049 - acc: 0.2500
Epoch 2/10
5/5 [==============================] - 0s 9ms/step - loss: 343.8528 - acc: 0.5833
Epoch 3/10
5/5 [==============================] - 0s 10ms/step - loss: 311.2560 - acc: 0.6389
Epoch 4/10
5/5 [==============================] - 0s 10ms/step - loss: 105.9106 - acc: 0.6944
Epoch 5/10
5/5 [==============================] - 0s 10ms/step - loss: 5.4681 - acc: 0.9722
Epoch 6/10
5/5 [==============================] - 0s 10ms/step - loss: 7.2145 - acc: 0.9444
Epoch 7/10
5/5 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - acc: 1.0000
Epoch 8/10
5/5 [==============================] - 0s 9ms/step - loss: 7.6304 - acc: 0.9722
Epoch 9/10
5/5 [==============================] - 0s 10ms/step - loss: 15.6056 - acc: 0.9167
Epoch 10/10
5/5 [==============================] - 0s 11ms/step - loss: 3.3143 - acc: 0.9722


In [29]:
#testing

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',  metrics= ['acc'])
test_scores = model.evaluate(x_test, y_test_ohe, verbose=1)

print("CNN loss: %.2f%%" % (100 - test_scores[1] * 100))
print("trained model directly, accuracy: {:5.2f}%".format(test_scores[1] * 100))

1/1 [==============================] - 0s 365ms/step - loss: 129.3904 - acc: 0.6667
CNN loss: 33.33%
trained model directly, accuracy: 66.67%


In [ ]:
# y_test2 = np.array(y_test)
# y_test2 = y_test.reshape(len(y_test),3)

In [ ]:
# x_train2,x_test2,y_train2,y_test2 = train_test_split(data, label, test_size=0.2, shuffle=True, random_state=2)

In [34]:
#print classification report
from sklearn import metrics
from imblearn.metrics import sensitivity_specificity_support

true_labels = ['Clear','Haze','Underwater']
labels = [0,1,2]
Y_pred = model.predict(x_test, batch_size=2)
preds = np.argmax(Y_pred, axis=1)
y_test_non_one_hot = np.argmax(y_test, axis=1)

# Save variable
acc = metrics.accuracy_score(y_test_non_one_hot, preds)
cm = metrics.confusion_matrix(y_test_non_one_hot, preds)
f1 = metrics.f1_score(y_test_non_one_hot, preds, average='micro')
precision = metrics.precision_score(y_test_non_one_hot, preds, average='micro')
recall = metrics.recall_score(y_test_non_one_hot, preds, average='micro')
classification_report = metrics.classification_report(y_test_non_one_hot, preds,labels=labels,target_names=true_labels)
print("Accuracy", acc)
print("Precision", precision)
print("Recall", recall)
print("F1-score", f1)
# print("Sensitivity Specificity Macro", sens_mac)
# print("Sensitivity Specificity Micro", sens_mic)
# print("Sensitivity Specificity Weighted", sens_weight)
print(classification_report)

print("Confusion Matrix")
print(cm)

5/5 [==============================] - 0s 6ms/step
Accuracy 0.6666666666666666
Precision 0.6666666666666666
Recall 0.6666666666666666
F1-score 0.6666666666666666
              precision    recall  f1-score   support

       Clear       1.00      0.25      0.40         4
        Haze       0.40      1.00      0.57         2
  Underwater       1.00      1.00      1.00         3

    accuracy                           0.67         9
   macro avg       0.80      0.75      0.66         9
weighted avg       0.87      0.67      0.64         9

Confusion Matrix
[[1 3 0]
 [0 2 0]
 [0 0 3]]
